# Generated by Django 5.2.16 on 2026-08-18 12:52

from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('orders', '0002_order_discount_order_discount_amount'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        AddIndexConcurrently(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        AddIndexConcurrently(
            model_name='order',
            index=models.Index(fields=['email'], name='orders_orde_email_88c705_idx'),
        ),
    ]
