# Generated by Django 5.2.16 on 2026-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address_line',
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
