# Generated by Django 5.2.16 on 2026-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
    ]
