# Generated by Django 5.2.16 on 2026-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Hex code e.g. #FF0000. Leave blank for multi-color.', max_length=7, null=True),
        ),
    ]
