# Generated by Django 5.2.16 on 2026-08-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_final_size_fk_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['category', 'display_order']},
        ),
        migrations.AddField(
            model_name='size',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Hex code e.g. #FF0000. Leave blank for multi-color.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='catalog.size'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('name', 'category')},
        ),
    ]
