# Generated by Django 5.2.16 on 2026-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_size_options_size_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Color name associated with this image, e.g. Blue, Black', max_length=50),
        ),
    ]
