# Generated by Django 5.2.16 on 2026-08-18 12:52

from django.db.transaction import atomic
import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('catalog', '0011_productimage_color'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='catalog_pro_is_acti_e6e001_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(fields=['gender', 'is_active'], name='catalog_pro_gender_d2c9f1_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(fields=['is_on_sale'], name='catalog_pro_is_on_s_383078_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['brand'], name='product_brand_trgm', opclasses=['gin_trgm_ops']),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='product_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        AddIndexConcurrently(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx'),
        ),
        AddIndexConcurrently(
            model_name='productvariant',
            index=models.Index(fields=['stock_quantity'], name='catalog_pro_stock_q_6ded5d_idx'),
        ),
    ]
